name: CI

concurrency:
  group: {% raw %}${{ github.ref }}{% endraw %}
  cancel-in-progress: true

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  test:

    runs-on: ubuntu-latest
    container: condaforge/mambaforge:latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Run CI
      run: |
        apt update && apt install -y git make

        make env
        
        make lint
        make test
        
        make docs

    - name: CodeCov
      uses: codecov/codecov-action@v4.1.1
      with:
        file: ./coverage.xml
        flags: unittests
        token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
